import type { NextPage } from "next";
import BasePage from "../components/BasePage/BasePage";
import PageSizeComponent from "../components/PageSizeComponent";
import Head from "next/head";
import TreeNode from "../components/TreeNode/TreeNode";
import {Node, TreeNodeProps} from '../interface/Node';

const treeData: Node[] = [
    {
      name: 'A',
      children: [
        {
          name: 'A1',
          children: [
            {
              name: 'A1a',
            },
            {
              name: 'A1b',
            },
          ],
        },
        {
          name: 'A2',
        },
      ],
    }
    ,
    {
      name: 'B',
      children: [
        {
          name: 'B1',
        },
        {
          name: 'B2',
        },
      ],
    }
  ];


const treeData1: Node = {
  name: 'Root',
  children: [
    {
      name: 'A',
      children: [
        {
          name: 'A1',
          children: [
            {
              name: 'A1a',
            },
            {
              name: 'A1b',
            },
          ],
        },
        {
          name: 'A2',
        },
      ],
    },
    {
      name: 'B',
      children: [
        {
          name: 'B1',
        },
        {
          name: 'B2',
        },
      ],
    },
  ],
};

 
const Home: NextPage = () => {
  return (
    /*
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hey Platzi Esto es una prueba23!</h1>
      </main>

      <footer></footer>
    </div>
    */
      
      <BasePage>
        <PageSizeComponent></PageSizeComponent>
        <header>
          <h1>Bienvenidos a mi página web2</h1>
        </header>
        <main>
          <p>Este es el cuerpo de mi página web. Aquí se puede incluir cualquier tipo de contenido, como texto, imágenes o videos.</p>
        </main>
        <h1>React Treeview Example</h1>
        <ul>
          <TreeNode node={treeData} />
        </ul>
      
        <footer>
        <p>Derechos de autor © 2023, Mi Empresa.</p>
      </footer>
    </BasePage>
    
  );
};

export default Home;
